### ISSUE TITLE
Caigudes del campus

### ISSUE THREAD

**Issue by deinok** [asicudl/campusvirtual#23]
Estarie be que duran les epoques de examens llançesiu mes servidor per atendre les peticions. Ja que els errors 503 Service Unavailable son sumament comuns.

Potse montar un Swarm de docker podrie arreglar aquestes caigudes en cas de sobrecarrega de usuaris
https://docs.docker.com/engine/swarm/

**Comment by sinmsinm** [comment]
Si gràcies, és una opció que estem valorant. Aquests dies esteu experimentant caigudes? Esteu d'examens?

**Comment by deinok** [comment]
Si, estem la gran majoria de estudiants de examens. Suposo que es per aixo que la gent entre mes al CV i acabe caient.

**Comment by sinmsinm** [comment]
Bé, primer comentar-te que em sap greu els errors que esteu experimentant. Encara estem ajustant els paràmetres dels servidors per a garantir el servei de campus virtual. La nova versió incorpora força canvis en el nucli del producte i canvia la forma en que consumeix els recursos.

El nombre de nodes que tenim ara mateix és força gran i no sembla que sigui el principal motiu pel qual produeixen aquests talls de servei, però si és cert que un creixement a partir de les necessitats en cada moment és l'opció més encertada.

Esperem resoldre o mitigar aquesta incidència el més aviat possible.
Gràcies pels teus comentaris.

**Comment by sinmsinm** [comment]
@deinok Hem aplicat canvis de configuració als diferents elements que formen part del campus virtual i en principi creiem que ja no veureu el "Service Unavailable" tan freqüentment com fins ara. Només en casos excepcionals on la càrrega sigui extremadament alta. T'agrairem que ens puguis confirmar si entre els usuaris que ho feu anar observeu la millora o encara ho seguiu tenint.

Disculpa les molèsties.
Àlex.

**Comment by deinok** [comment]
Okey, si jo o algun conegut experimente aquestes caigudes, ho reportare. 
Gracies @sinmsinm

**Comment by sinmsinm** [comment]
Si no heu experimentat més 503s tancaria la incidència.

**Comment by deinok** [comment]
@sinmsinm Okey gracies
